### ISSUE TITLE
 Not a valid object name --no-gpg-sign

### ISSUE THREAD

**Issue by Thermionix** [joeyh/github-backup#24]
Installed with cabal

     github-backup-1.20140721
    ~$ git --version
    git version 1.9.1
    ~$ github-backup thermionix
    .....
    Gathering metadata for git://github.com/mdengler/pastgit.git ...
    Gathering metadata fatal: Not a valid object name --no-gpg-sign
    for git://github.com/ojarva/pastgit.git ...
    ....
    github-backup: user error (git ["--git-dir=/media/tank/sync/github-backup/arch-scripts/.git","--work-tree=/media/tank/sync/github-backup/arch-scripts","commit-tree","4b825dc642cb6eb9a060e54bf8d69288fbee4904","--no-gpg-sign"] exited 128)

**Comment by joeyh** [comment]
Assuming this was a case of building with a newer version of git than it was subsequently used with, which I don't support.
