### ISSUE TITLE
pushable (ssh or https) remotes

### ISSUE THREAD

**Issue by cben** [joeyh/github-backup#29]
Having run github-backup, it was convenient to work on one of the repos inside the backup but pushing back complains:

```
fatal: remote error: 
  You can't push to git://github.com/cben/sandbox.git
  Use https://github.com/cben/sandbox.git
```

Github allows pushing only via ssh and https, not `git://` URLs.
Would it be possible for github-backup to configure ssh or https remotes for everything?
Assuming you're fetching via `git://` for good reason, you can still configure a different `pushurl`:

```
git remote set-url --push origin git@github.com:cben/sandbox.git
```

**Comment by jwilk** [comment]
FYI, you can configure git to always use HTTPS or SSH for GitHub.
For example, I have this my config:
```
[url "https://github.com/"]
insteadOf = git://github.com/

[url "git@github.com:"]
pushInsteadOf = git://github.com/
pushInsteadOf = https://github.com/
```

**Comment by teeks99** [comment]
As others have pointed out, this doesn't make a lot of sense for the vast majority of what is downloaded. Additionally, as this is explicitly a backup tool, I don't think it needs to support uploading at all. That said, I have seen instances where the https sockets to githubs servers have been flaky and a ssh socket works better. It might be nice to have an option to let the user specify their desired transport.

**Comment by joeyh** [comment]
You should be abe to use git's `insteadOf` configuration to rewrite the
http urls to ssh urls.

-- 
see shy jo
