### ISSUE TITLE
Ability to disable backing up of forks

### ISSUE THREAD

**Issue by nurupo** [joeyh/github-backup#31]
I'm backing up several repos ([96 repos](https://github.com/nurupo-backup) as of now). I have put github-backup in cron to run every 3 hours (mostly because I noticed that on average it was running for about 2h 50min before terminating) starting from 1st of January till today, which is about 32-40 runs in total, but it still can't keep up with repos.

Just today, four days later, it got to backing up my own fork of one of repos, creating all the branches I have in my fork (i.e. it's the very first backup of my fork) -- it's still isn't finished with the initial backup of forks. Also, the original repos are out of date -- code commited and pushed on 2nd of January is not yet pulled.

I would rather want it to keep only the starred repos up to date and forget about automatically backing up forks. If I would want it to backup a fork, I would separately star it (which leads to another issue, since I would have two starred repos with the same name, which might break github-backup).

**Comment by nurupo** [comment]
Actually, I noticed a bit later that repos (at least some of them) are actually up to date (the origin/master branch gets updated). I just had to manually merge origin/master into master.

**Comment by thkoch2001** [comment]
+1 I had a fork of https://github.com/nylira/prism-break which has just a few hundret forks, which is not much for a popular repository. But most of the forks are just kind of 'bookmarks' with no added information. Fetching all this forks takes ages.

I'm afraid that the github API doesn't help to filter only interesting forks.

**Comment by thkoch2001** [comment]
The (forks api response)[https://developer.github.com/v3/repos/forks/] has two fields, created_at and pushed_at. It seems, that pushed_at is less or equal to created at if nothing new has been pushed to the fork.

I don't know the semantic of the updated_at field. Maybe it's about wiki and issues? I've seen cases of Updated_at field less than, equal to and greated than created_at.

**Comment by ctrlcctrlv** [comment]
Backing up all the forks for large repos is obnoxious default behavior. 

Lots of people just fork and never do anything, hardly any forks are interesting.

Please add option to disable.
