### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by jeffsegal** [joeyh/github-backup#41]
FYI, I ran into a few dependency issues while building the module in Cygwin. I had to manually install `network`, then modify `github-backup.cabal` to add the following modules to the `Build-Depends` entry for `github-backup` & `gitriddance`: 

* `utf8-string`
* `Win32`
* `setenv`

I also had to run the Cygwin Terminal as Administrator in order to install `network`. 

Ultimately, the build succeeded after making those modifications.

**Comment by joeyh** [comment]
Fixed in bfe6a3c988f9ff64b9bdceb4de977dcca123810d

-- 
see shy jo
