### ISSUE TITLE
Add support for OAuth tokens instead of username/password

### ISSUE THREAD

**Issue by fingolfin** [joeyh/github-backup#55]
Would this be possible? I don't like giving my passwords to scripts, or letting it hang around in env variables.

See https://help.github.com/articles/git-automation-with-oauth-tokens/

**Comment by joeyh** [comment]
oath support was recently added to the haskell github library, so it
would be a simple matter of plumbing to expose it.

-- 
see shy jo

**Comment by fingolfin** [comment]
Thanks
